project:
  type: website
  output-dir: docs

website:
  title: "T. OHIGASHI"
  site-url: "https://github.com/taka-ohi/taka-ohi.github.io"
  navbar:
    background: dark
    foreground: light
    left:
      - text: "Home"
        href: index.qmd
      - text: "Publication"
        href: publication.qmd
    right:
      - href: index.qmd
        text: "English"
        icon: globe
      - href: index_jp.qmd
        text: "日本語"
        icon: globe
    page-navigation: true

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

