project:
  type: website
  output-dir: docs

website:
  title: "T. OHIGASHI"
  site-url: "https://github.com/taka-ohi/taka-ohi.github.io"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: publication.qmd
        text: Publication
      - href: japanese.qmd
        text: Japanese (日本語)

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

