---
title: "生態学・執筆関係リンク集"
format:
  html:
    css: my-custom-style2.css
---

::: {style="text-align: center;"}
これまでに参考にしたウェブサイトや書籍など
:::

<br>

# 生態学

## 理論

#### 生態学の用語など

-   基礎生態学 <a href="https://hosho.ees.hokudai.ac.jp/tsuyu/top/lecture/envcons-j.html#com" target="_blank">(北海道大学・露崎先生のサイト)</a>
-   【書籍】生態学入門・第２版 (日本生態学会, 2012)

#### 群集生態学

-   群集生態学における共存理論の現代的統合 <a href="https://www.jstage.jst.go.jp/article/seitai/71/2/71_35/_article/-char/ja/" target="_blank">(篠原ら, 2021)</a>
-   細菌群集の時空間分布と物質循環をつなぐ：細菌とメタ群集理論 <a href="https://www.jstage.jst.go.jp/article/seitai/57/3/57_KJ00004816812/_article/-char/ja/" target="_blank">(三木, 2007)</a>
-   【書籍】ミッテルバッハ・マギル群集生態学 (Mittelbach & McGill 著; 門脇ら 訳, 2023)

#### 系統樹

-   分子系統解析の最前線 <a href="https://www.jstage.jst.go.jp/article/jsbibr/2/1/2_jsbibr.2021.7/_html/-char/ja" target="_blank">(松井, 2021)</a>

<br>

## データ解析

#### 統計

-   実験計画の立て方とRを用いた分散分析：実験計画に応じた分散分析の実行 <a href="https://www.jstage.jst.go.jp/article/weed/56/1/56_1_24/_article/-char/ja/" target="_blank">(水口, 2011)</a>
-   生態学のデータ解析 - 統計学授業 2019 <a href="https://kuboweb.github.io/-kubo/ce/EesLecture2019.html" target="_blank">(久保先生のサイト)</a>
-   <a href="https://logics-of-blue.com/" target="_blank">Logics of Blue</a>

#### アンプリコンシークエンスデータ解析

-   <a href="https://benjjneb.github.io/dada2/ITS_workflow.html" target="_blank">DADA2 ITS Pipeline Workflow (1.8)</a>
-   phyloseq による DADA2 処理後の統計解析 <a href="https://ushio-ecology-blog.blogspot.com/2021/04/20210428blogger0015.html?spref=tw" target="_blank">(Ushio's blog)</a>

#### 生物群集（多変量）解析

-   生物群集解析のための類似度とその応用：Rを使った類似度の算出、グラフ化、検定 <a href="https://www.jstage.jst.go.jp/article/seitai/61/1/61_KJ00007176266/_article/-char/ja/" target="_blank">(土居ら, 2011)</a>
-   【書籍】Rによる数値生態学 (Borcardら 著; 吉原ら訳, 2023)

#### ネットワーク解析

-   Rとigraphを使ったネットワーク解析と可視化 <a href="https://www.nemotos.net/igraph-tutorial/NetSciX_2016_Workshop_ja.html" target="_blank">(Ognyanova 著; 田村&根本 訳)</a>
-   【書籍】DNA情報で生態系を読み解く (東樹, 2016)

#### Empirical Dynamic Modelling

-   rEDM を用いた Empirical Dynamic Modeling: (1) 動態の再構成 <a href="https://ushio-ecology-blog.blogspot.com/2019/12/20191205blogger0004.html" target="_blank">(Ushio's blog)</a>

#### 再現可能な解析をする

-   解析するときのルールあれこれ <a href="https://ushio-ecology-blog.blogspot.com/2020/05/20200507blogger0012.html" target="_blank">(Ushio's blog)</a>

#### 可視化

-   <a href="https://r-graph-gallery.com/" target="_blank">The R Graph Gallery</a>

<br>

## 実験

#### フィールド研究の実験手法

-   <a href="https://sites.google.com/view/ecology-method-portal/home" target="_blank">生態系科学　手法動画ポータル</a>

<br>

# 執筆

## 論文

#### 論文の構成や書き方

-   <a href="https://besjournals.onlinelibrary.wiley.com/hub/journal/13652745/journal-resources/guide-to-scientific-writing" target="_blank">The British Ecological Society Short Guide to Scientific Writing</a>
-   【書籍】まったく新しいアカデミック・ライティングの教科書 (阿部, 2024)
-   【書籍】できる研究者の論文生産術 (シルヴィア 著; 高橋 訳, 2015)

#### 各科学雑誌出版機関のプレプリントに対するポリシー

-   <a href="https://en.wikipedia.org/wiki/List_of_academic_publishers_by_preprint_policy" target="_blank">List of academic publishers by preprint policy</a>

<br>

## 申請書

#### 学振申請書（※年度ごとの仕様の変更に注意）

-   論文ゼロでも学振DC1に面接経由で採用された申請書の書き方のコツと面接対策ポイント <a href="https://ocoshite.me/how-to-get-gakushin-dc1" target="_blank">(minoblog)</a>
-   学振特別研究員になるために <a href="http://www.rpd.titech.ac.jp/jsps_tokken/ohue2023-1_3.pdf" target="_blank">(東京科学大学・大上先生のスライド)</a>
-   学振申請書を書く心得 <a href="https://docs.google.com/presentation/d/e/2PACX-1vS75s7h_GwsQnwG5Hq6DRfqkXVUEtJ4V1uzVCX0M0fAO64IGFDeCZHDd8B2lpi8L8Q3fdaXvFZlOsq4/pub?start=false&loop=false&delayms=3000" target="_blank">(拙スライド)</a>

<br>

## 全般

#### 文章の書き方

-   技術を伝えるときの執筆の方針 <a href="https://logics-of-blue.com/writing-policy-when-conveying-technology/" target="_blank">(Logics of Blue)</a>

#### 雑誌名の略称の検索

-   <a href="https://woodward.library.ubc.ca/woodward/research-help/journal-abbreviations/" target="_blank">Science and Engineering Journal Abbreviations</a>

#### 知的生産について

-   【書籍】イシューからはじめよ (安宅, 2010)
