---
title: "出版物"
format:
  html: 
    css: my-custom-style.css
---

# 研究論文

## プレプリント

-   Darnajoux, R.†\*, Haynes, S., Renaudin, M.†, Magain, N., Dani, S., Koonin, S., Miadlikowska, J., Uchida, Y., **Ohigashi, T.**, Haughland, D., Lutzoni, F., Bellenger, J.P. & Zhang, X.\
    "Global role of vanadium for nitrogen fixation in extratropical forests"<a href="https://doi.org/10.22541/au.172463318.84381995/v1" target="_blank"><br>*Authorea*</a>

<br>

## 出版/受理済

### 2025

3.  **Ohigashi, T.**\*, Mori, S., Tago, K., Ohbayashi, T., Hara, S. & Uchida, Y. (*in press*)\
    "Differential responses of soil ammonia-oxidizing bacterial and archaeal communities to land-use change in Zambia"<br>*Microbes and Environments*

### 2024

2.  Soe, N. C., Yohannes, Y. B., **Ohigashi, T.**, Nakata, H., Tatsumi, C., Uchida, Y., Mufalo, W., Ito, M., Sato, T., Igarashi, T., Ikenaka, Y., Ishizuka, M., & Nakayama, S. M. M.\* (2024)\
    "Effect of chicken manure amendment on lead burden in mice: Exposure to lead-spiked soil" <a href="https://doi.org/10.1007/s11368-024-03769-y" target="_blank"><br>*Journal of Soils and Sediments*, 24, 2001–2011</a>

### 2021

1.  **Ohigashi, T.**, Schloter, M., Schulz, S., Munthali, K., & Uchida, Y.\* (2021)\
    "Changes in soil prokaryotic diversity in response to land-use changes in sub-Saharan Africa" <a href="https://doi.org/10.3390/soilsystems5040062" target="_blank"><br>*Soil Systems*, 5(4), 62</a>
